<?php
$showNew = $this->identity == null ? 'style="display:none"' : '';
$board = $this->board;
echo <<<EOHTML
<div class='de_button newtopic' $showNew>
	NEW TOPIC
</div>
<article class='forum lift'>
	<table>
		<thead>
			<tr>
				<th>
					{$board['title']}
				</th>
				<td>
					Views
				</td>
				<td>
					Replies
				</td>
				<td>
					Last Post
				</td>
			</tr>
		</thead>
		<tbody>
EOHTML;
if (mysqli_num_rows($this->topics) == 0)
{
	echo <<<EOHTML
			<tr>
				<td id=notopics colspan=4>
					No topics here...
				</td>
			</tr>
EOHTML;
}
while ($topic = mysqli_fetch_array($this->topics))
{
	$time = date('g:ia, M j Y',$topic['poster_time']);
	$url = $this->url(array('controller' => 'topic', 'action' => 'view', 'id' => $topic['id']), null, true);
	$sticky = $topic['sort'] == 0 ? '' : '<img src=/img/sticky.png />';
	$locked = $topic['locked'] ? "<img src='/img/lock.png'/> " : "";
	echo <<<EOHTML
			<tr>
				<td>
					$sticky
					$locked<a href=$url>{$topic['title']}</a>
				</td>
				<td>
					{$topic['views']}
				</td>
				<td>
					{$topic['replies']}
				</td>
				<td>
					<p class={$topic['poster_class']}>{$topic['poster_name']}</p>
					<p>$time</p>
				</td>
			</tr>
EOHTML;
	}
	
	echo <<<EOHTML
		</tbody>
	</table>
</article>
<div class='de_button newtopic' $showNew>
	NEW TOPIC
</div>
<section class=post id=newtopicsection style=display:none; >
	<header>
		<div>New Topic</div>
	</header>
	<article>
		<form id=newtopicform>
			<table>
				<tr>
					<th>Title</th>
					<td><input type=text id=myTitle name=title class=required /></td>
				</tr>
				<tr>
					<th>Post</th>
					<td><textarea id="myMessage" name="message" class="required" rows="6" cols="80"></textarea></td>
				</tr>
				<tr>
					<th></th>
					<td><input class=de_button type=submit value=Submit /></td>
				</tr>
				<tr>
					<th></th>
					<td><input class=de_button id=cancel type=button value=Cancel /></td>
				</tr>
				<tr>
					<th></th>
					<td><div class=de_button>Preview<input id=preview type=checkbox checked /></div></td>
				</tr>
			</table>
		</form>
	</article>
	<h2>Post Preview</h2>
	<article id=previewpost>
	</article>
</section>
EOHTML;
$this->minifyHeadScript()->appendScript(<<<JS
window.addEvent('domready',function() {
	var previewUpdate = function()
	{
		html = $('previewpost').get('html');
		editor = tinymce.get('myMessage').getContent();
    	if (html.contains('iframe') && editor.contains('iframe'))
    	{
    		$('preview').set('checked',false);
    		$('preview').set('disabled',true);
    		$$('#preview !> div').setStyle('color','#A00');
    	} 
    	else 
		{
			$('preview').erase('disabled');
			$$('#preview !> div').setStyle('color','inherit');
		}
		
		if ($('preview').get('checked'))
		{
			$('previewpost').set('html',editor);
		}
	};
	
	$$('#preview !> div, #preview').addEvent('click',function()
	{
		$('preview').set('checked',!$('preview').get('checked'));
		previewUpdate();
	});
	
	tinyMCE.init({
			// General options
			mode : "exact",
			elements : "myMessage",
			theme : "advanced",
			skin : "o2k7",
			skin_variant : "black",
			relative_urls : false,
			setup: function(ed)	{
				ed.onKeyUp.add(function(ed) {
					previewUpdate();
				});
			},
			plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
	
	        // Theme options
	        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect,|,bullist,numlist|,outdent,indent,blockquote",
	        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor|,ltr,rtl|,charmap,emotions,iespell,media,advhr|,hr,removeformat,visualaid",
	        theme_advanced_buttons3 : "tablecontrols,|,insertlayer,moveforward,movebackward,absolute,|,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak",
	        theme_advanced_toolbar_location : "top",
	        theme_advanced_toolbar_align : "left",
	        theme_advanced_statusbar_location : "bottom",
	        theme_advanced_resizing : true,
		    width: "100%",
		    height: "400"
	});
	
	var originals = $$('#page > div, #page > article');
	var forms = $$('#newtopicsection');
	
	$$('.newtopic').addEvent('click',function(e) {
		e.stop();
		originals.dissolve();
		forms.reveal();
	});

	$('cancel').addEvent('click', function(e) {
		e.stop();
		originals.reveal();
		forms.dissolve();
	});

	$('newtopicform').addEvent('submit', function(e) {
		e.stop();
		if ($('myTitle').value != "" && tinymce.get('myMessage').getContent() != "") {
			$('myMessage').value = tinymce.get('myMessage').getContent();
			new Request.HTML({
				url : baseUrl+'/topic/add/id/{$board['id']}',
				append: $('page'),
				evalScripts: true,
				onSuccess : function() {
					$('myTitle').value = null;
					tinymce.get('myMessage').setContent("");
					originals.reveal();
					forms.dissolve();
					if ($('notopics') != null)
						$('notopics').dissolve();
				}
			}).post($('newtopicform')).send();
		}
	}); 
});
JS
);