<style>
body {
    background-attachment: fixed;
    background-clip: border-box;
    background-color: #0A0A11;
    background-image: url("/img/bg.png");
    background-origin: padding-box;
    background-repeat: no-repeat;
    background-size: 100% auto;
}
div#container {
	margin: 300px auto;
	width: 1000px;
	border: 1px solid #555;
	background: white;
	padding: 50px;
}
div#images img + img {
	position: relative;
	bottom: 50px;
}
</style>
<body>
<div id="container">
	<div id="images">
		<img src="/img/emblem.png"/>
		<img src="/img/de_logo_small.png"/>
	</div>
	<div id="content">
		<p>
			Your browser is incompatible with the new Dishonor Elite website. Please update your browser.
		</p>
		<p>
			<a href="www.google.com/chrome">Google Chrome</a><br/>
			<a href="http://www.mozilla.org/en-US/firefox/new/">Mozilla Firefox</a><br/>
			<a href="http://windows.microsoft.com/en-US/internet-explorer/downloads/ie">Internet Explorer 9</a><br/>
		</p>
	</div>
</div>
</body>
</html>