<?php
$topic = $this->topic;
$forumName = stripslashes($topic['f_title']);
$forumUrl = $this->url(array('controller' => 'forum', 'action' => 'index', 'id' => $topic['f_id']), null, true);
$boardName = stripslashes($topic['b_title']);
$lock = $topic['locked'] ? "<img src='/img/lock.png'/> " : "";
$sticky = $topic['sort'] == 10 ? "<img src='/img/sticky.png'/> " : "";
$boardUrl = $this->url(array('controller' => 'board', 'action' => 'view', 'id' => $topic['b_id']), null, true);
$i = 1;
echo <<<EOHTML
<section id=posts>
<header id=topic class=lift>
	<p><a href={$forumUrl}>{$forumName}</a> &raquo; <a href={$boardUrl}>{$boardName}</a></p>
	<h1>$lock$sticky{$topic['title']}</h1>
</header>
EOHTML;

if ($this->identity['rank'] > 29)
{
	if ($topic['locked']) {
		$url = $this->url(array('controller' => 'topic', 'action' => 'lock', 'id' => $topic['id'], 'lock' => 0),null,true);
		echo "<a href='$url' class='de_button' style='margin:0 10px 10px 0;'><img src='/img/lock.png'/> UNLOCK</a>";
	} else {
		$url = $this->url(array('controller' => 'topic', 'action' => 'lock', 'id' => $topic['id'], 'lock' => 1),null,true);
		echo "<a href='$url' class='de_button' style='margin:0 10px 10px 0;'><img src='/img/lock.png'/> LOCK</a>";
	}
	
	if ($topic['sort'] == 10) {
		$url = $this->url(array('controller' => 'topic', 'action' => 'sticky', 'id' => $topic['id'], 'sort' => 0),null,true);
		echo "<a href='$url' class='de_button' style='margin:0 10px 10px 0;'><img src='/img/sticky.png'/> UNSTICKY</a>";
	} else {
		$url = $this->url(array('controller' => 'topic', 'action' => 'sticky', 'id' => $topic['id'], 'sort' => 10),null,true);
		echo "<a href='$url' class='de_button' style='margin:0 10px 10px 0;'><img src='/img/sticky.png'/> STICKY</a>";
	}
}

while ($post = mysqli_fetch_array($this->posts))
{
	$class = $post['c_class'];
	$name = $post['c_name'];
	$date = date('g:ia, m/j/Y',$post['time']);
	$text = stripslashes($post['text']);
	
	if (!$this->topic['locked'])
	{
		$deleteDiv = (($this->identity['id'] == $post['a_id']) && !$post['deleted']) ? "<div class='de_button deletepost' data={$post['id']}>DELETE</div>" : "";
		$replyDiv = "<div class='de_button replypost'>REPLY</div>";
	} else {
		$deleteDiv = '';
		$replyDiv = '';
	}
	echo <<<EOHTML
<section class=post rel=$post[id]>
	<aside>
		<img class='wow-icon' src=$post[c_thumb] />
		<div class=$class>$name</div>
<!--	<div><img src='/img/achievements.gif'/>  9303</div> -->
	</aside>
	<div style="overflow:auto;">
		<header>
			<div class=num>#$i</div>
			<div class=time>$date</div>
		</header>
		<article>
			{$text}
		</article>
		<footer>
			$replyDiv
			$deleteDiv
		</footer>
	</div>
</section>
EOHTML;
	$i++;
}
echo '</section>';

if (!$this->topic['locked'])
{
	echo $this->replytotopic($topic['id']);
	$this->minifyHeadScript()->appendScript(<<<JS
window.addEvent('domready',function() {
	var previewUpdate = function()
	{
		html = $('previewpost').get('html');
		editor = tinymce.get('myMessage').getContent();
    	if (html.contains('iframe') && editor.contains('iframe'))
    	{
    		$('preview').set('checked',false);
    		$('preview').set('disabled',true);
    		$$('#preview !> div').setStyle('color','#A00');
    	} 
    	else 
		{
			$('preview').erase('disabled');
			$$('#preview !> div').setStyle('color','inherit');
		}
		
		if ($('preview').get('checked'))
		{
			$('previewpost').set('html',editor);
		}
	};
	
	$$('#preview !> div, #preview').addEvent('click',function()
	{
		$('preview').set('checked',!$('preview').get('checked'));
		previewUpdate();
	});

	tinyMCE.init({
			// General options
			mode : "exact",
			elements : "myMessage",
			theme : "advanced",
			skin : "o2k7",
			skin_variant : "black",
			relative_urls : false,
			setup: function(ed)	{
				ed.onKeyUp.add(function(ed) {
					previewUpdate();
				});
			},
			plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
	
	        // Theme options
	        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect,|,bullist,numlist,|,outdent,indent,blockquote",
	        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,ltr,rtl,|,charmap,emotions,iespell,media,advhr,|,hr,removeformat,visualaid",
	        theme_advanced_buttons3 : "tablecontrols,|,insertlayer,moveforward,movebackward,absolute,|,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak",
	        theme_advanced_toolbar_location : "top",
	        theme_advanced_toolbar_align : "left",
	        theme_advanced_statusbar_location : "bottom",
	        theme_advanced_resizing : true,
		    width: "100%",
		    height: "400"
	});
	
	var myFx = new Fx.Scroll(window);
	
	if ({$this->post} != 0)
	{
		myFx.toElement($$('.post[rel={$this->post}]')[0]);
	}
	
	var fadeAndScroll = function(posts) {
		posts.addEvents({
			mouseenter : function() {
				this.getElements('footer div').fade(1);
			},
			mouseleave : function() {
				this.getElements('footer div').fade(0.3);
			}
		});
		
		posts.getElement('.replypost').addEvent('click', function(e){
			e.stop();
			$('replysection').reveal();
			myFx.toElementCenter('replysection');
		});
	};

	fadeAndScroll($$('#posts .post'));
	
	$('replypost').addEvent('submit', function(e) {
		e.stop();
		if (tinymce.get('myMessage').getContent() != "") {
			$('myMessage').value = tinymce.get('myMessage').getContent();
			new Request.HTML({
				url : baseUrl+'/post/add/type/topic/id/{$topic['id']}',
				append : $('posts'),
				onSuccess : function() {
					tinymce.get('myMessage').setContent("");
					previewUpdate();
					$('replysection').dissolve();
					fadeAndScroll($$('#posts .post').getLast());
				}
			}).post($('replypost')).send();
		}
	}); 

	$$('.deletepost').addEvent('click', function(e) {
		e.stop();
		if (confirm("Are you sure you want to delete this post?"))
		{
			var id = this.get('data');
			var buttons = this;
			new Request.HTML({
				url : baseUrl+'/post/delete/id/' + id ,
				update : this.getParent().getPrevious(),
				onSuccess : function() {
					buttons.dissolve();
				}
			}).send();
		}
	}); 
});
JS
);
}

$this->minifyHeadScript()->appendScript(<<<JS
window.addEvent('domready',function() {
	var myFx = new Fx.Scroll(window);
	
	if ({$this->post} != 0)
	{
		myFx.toElement($$('.post[rel={$this->post}]')[0]);
	}
});
JS
);