<?php
echo <<<EOHTML
<section class='lift postframe'>
	<header>
		<h1>Forgot My Password</h1>
	</header>
	<article>
		<form id=forgotpw method=post>
		<table>
		<tr>
			<th>Email Address</th>
			<td><input type=email name=email class="required validate-email" /></td>
		</tr>
		<tr>
			<td></td>
			<td><div>{$this->recaptcha}</div></td>
		</tr>
		<tr>
			<th></th>
			<td><input type=submit value=Submit />
		</tr>
		</table>
		</form>
	</article>
</section>
EOHTML;
 
$this->minifyHeadScript()->appendScript(<<<JS
window.addEvent('domready', function() {

	var pwVal = new Form.Validator($('changepwform'));
	
	$$('input[type=submit]').addEvent('click', function(e) {
		e.stop();
		if (!pwVal.validate()) {
			DEmessenger('Please enter a valid email address');
		}
		else
		{
			$('forgotpw').submit();
		}
	});
});
JS
);