<?php
if (count($this->mounts) == 0)
{
	echo "<div style='text-align:center;'><em>None</em></div>";
}
else 
{
	$wh = new WowHead();
	$i = 0;
	echo "<table id='char-mounts'><tbody><tr><th colspan='3'>Mounts</th>";
	foreach (array_reverse($this->mounts) as $mount)
	{
		if ($i++ % 3 == 0) {
			echo "</tr><tr>";
		}
		$name = $wh->getData("http://www.wowhead.com/spell=$mount",'name_enus');
		$icon = $wh->getData("http://www.wowhead.com/spell=$mount",'icon');
		echo "<td><img class='wow-icon' src='http://us.media.blizzard.com/wow/icons/36/$icon.jpg'/><a target='_blank' href='http://www.wowhead.com/spell=$mount'>$name</a></td>";
	}
	echo "</tr></tbody></table>";
}
?>
<style>
#char-mounts {
	margin: 10px auto;
	border-collapse: collapse;
	border: 2px outset #0398FF;
	box-shadow: 0 0 10px #FFFFFF;
}
#char-mounts td {
	border: 1px inset #0398FF;
	padding: 5px 10px;
}
#char-mounts td a {
    bottom: 13px;
    left: 5px;
    position: relative;
}
#char-mounts tr:nth-child(even) td:nth-child(even), #char-mounts tr:nth-child(odd) td:nth-child(odd) {
	background: #222;
}
</style>
