<?php
echo <<<EOHTML
<div>
	<table id=main-stats-table>
		<tbody>
			<tr>
				<td>
					<h1>Base</h1>
					<table>
EOHTML;
foreach ($this->base as $name => $key)
{
	echo "<tr><th>$name</th><td>{$this->stats[$key]}</td></tr>";
}
echo <<<EOHTML
					</table>
				</td>
				<td>
					<h1>Melee</h1>
					<table>
EOHTML;
foreach ($this->melee as $name => $key)
{
	echo "<tr><th>$name</th><td>{$this->stats[$key]}</td></tr>";
}
echo <<<EOHTML
					</table>
				</td>
				<td>
					<h1>Spell</h1>
					<table>
EOHTML;
foreach ($this->spell as $name => $key)
{
	echo "<tr><th>$name</th><td>{$this->stats[$key]}</td></tr>";
}
echo <<<EOHTML
					</table>
				</td>
				<td>
					<h1>Ranged</h1>
					<table>
EOHTML;
foreach ($this->ranged as $name => $key)
{
	echo "<tr><th>$name</th><td>{$this->stats[$key]}</td></tr>";
}
echo <<<EOHTML
					</table>
				</td>
				<td>
					<h1>Defense</h1>
					<table>
EOHTML;
foreach ($this->defense as $name => $key)
{
	echo "<tr><th>$name</th><td>{$this->stats[$key]}</td></tr>";
}
echo <<<EOHTML
					</table>
				</td>
				<td>
				</td>
			</tr>
		</tbody>
	</table>
</div>
EOHTML;
?>
<style>
#main-stats-table,#main-stats-table table {
	width: 100%;
	margin-bottom: 15px;
	border-collapse: collapse;
}

#main-stats-table>tbody>tr:nth-child(2) >td {
	border-top: 1px dotted #aaa;
	border-bottom: 1px dotted #aaa;
}
#main-stats-table th, #main-stats-table td {
	padding: 2px 10px 2px 0;
}
#main-stats-table td {
	vertical-align: top;
}

#main-stats-table table th {
	text-align: left;
}
#main-stats-table table tr:not(:first-child) th, #main-stats-table table tr:not(:first-child) td {
	border-top: 1px inset #0398FF;
}
#main-stats-table h1 {
	text-align: center;
	font-size: 16px;
	margin: 10px;
	font-weight: 700;
}
</style>
