<section class='postframe lift shadow'>
<?php
if ($this->guild)
{
	$data = $this->guild->getData();
	$url = $this->url(array('controller' => 'armory', 'action' => 'roster', 'guild' => $data['name'], 'realm' => $data['realm']),null,true);
	echo <<<EOHTML
		<table id='guild-head'>
			<tbody>
				<tr>
					<td id='guild-name' class='side-$data[side]'>$data[name]</td>
					<td id='guild-level'>$data[level]</td>
				</tr>
				<tr>
					<td id='guild-realm'>$data[realm]</td>
					<td id='guild-points'>$data[achievementPoints] <img src='/img/achievements.gif'/></td>
				</tr>
				<tr>
					<td colspan='2'><a href='$url'>View Roster</a></td>
				</tr>
			</tbody>
		</table>
		<table id='guild-achieve'>
			<thead>
				<tr>
					<th colspan='3'>Recent Achievements</th>
				</tr>
			</thead>
			<tbody>
EOHTML;
$i = 0;
$wh = new Wowhead();
foreach ($this->guild->getAchievements('timestamp','desc') as $achievement)
{
	$date = date('g:ia, M j Y',$achievement['timestamp']/1000);
	$url = "http://www.wowhead.com/achievement=$achievement[id]";
	$icon = str_replace('-','',$wh->getData($url,'icon'));
	echo <<<EOHTML
				<tr>
					<td>
						<a href='$achievement[url]'><img src='http://us.media.blizzard.com/wow/icons/56/$icon.jpg' class='wow-icon'/></a>
					</td>
					<td>
						<a href='$achievement[url]' class='q'>$achievement[name]</a>
					</td>
					<td>
						$date
					</td>
				</tr>
EOHTML;
if ($i++ >= 5) break;
}
echo "</tbody></table><table id='guild-perks'><thead><tr><th colspan='4'>Guild Perks</th></tr></thead><tbody>";
foreach (array_reverse($this->guild->getPerks()) as $perk)
{
	echo <<<EOHTML
				<tr>
					<td>
						<a href='{$perk['wowhead']}'><img src='http://us.media.blizzard.com/wow/icons/56/{$perk['spell']['icon']}.jpg' class='wow-icon'/></a>
					</td>
					<td>
						<a href='{$perk['wowhead']}'>{$perk['spell']['name']}</a>
					</td>
					<td>
						{$perk['spell']['description']}
					<td>
						$perk[guildLevel]
					</td>
				</tr>
EOHTML;
}
echo "</tbody></table>";
}
else
{
	echo "<h1 style='text-align:center'>Guild not found</h1>";
}
?>
</section>
<style>
#guild-perks tbody td:last-child {
	font-size: 16px;
	font-weight: bold;
}
#guild-achieve, #guild-perks {
	width: 100%;
	border-collapse: collapse;
	margin: 20px auto;
}
#guild-achieve thead th, #guild-perks thead th {
	font-size: 16px;
	font-weight: bold;
}
#guild-achieve tbody tr:not(:first-child) td, #guild-perks tbody tr:not(:first-child) td {
	border-top: 1px inset #aaa;
}
#guild-achieve tbody tr td:nth-child(2) a {
	font-size: 14px;
}
#guild-head {
	border-collapse: collapse;
	width: 100%;
}
#guild-head tbody tr:last-child {
	border-bottom: 2px inset #0398FF;
}
#guild-name, #guild-level {
	font-size: 24px;
	font-weight: bold;
}
#guild-name.side-0 {
	text-shadow: 0 0 10px #0389FF;
}
#guild-name.side-1 {
	text-shadow: 0 0 10px red;
}
#guild-realm, #guild-points {
	font-size: 18px;
}
#guild-level, #guild-points {
	text-align: right;
}
</style>